# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
changelog:
  categories:
    - title: Bugfixes
      labels: [bug]
    - title: Improvements
      labels: ['*']
      exclude:
        labels: [meta] # Only needed because Meta must be last
    - title: Meta
      labels: [meta]
