schema:
  - ./schema.docs.graphql
documents:
  - 'source/**/*.gql'
  - 'source/**/*.graphql'
extensions:
  codegen:
    generates:
      ./source/github-helpers/github-graphql-types.ts:
        plugins:
          - typescript
          - typescript-operations
        config:
          strictScalars: true
          immutableTypes: true
          avoidOptionals: false
          namingConvention:
            typeNames: pascal-case#pascalCase
            enumValues: upper-case#upperCase
          scalars:
            DateTime: string
            URI: string
            HTML: string
            GitObjectID: string
            GitSSHRemote: string
            X509Certificate: string
            Date: string
            Base64String: string
            BigInt: number
            PreciseDateTime: string
            GitTimestamp: string
            CustomPropertyValue: string | number | boolean
            GitRefname: string
