name: 🐛 Report a bug
description: '___'
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting a bug! ⛰

        Help us replicate the issue by filling in this form.
  - type: checkboxes
    attributes:
      label: "Please ensure:"
      options:
        - label: The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
          required: true
  - type: textarea
    attributes:
      label: Describe the problem and how to replicate it
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots/video/gif showing the issue, if it’s visual
      description: Files can be dropped in this field
  - type: textarea
    attributes:
      label: Console errors, if any
      render: shell
  - type: input
    attributes:
      label: Example URL
      description: A REAL URL where the bug appears. If it happens on a private repo, find an equivalent public URL, even if it doesn't happen there.
      placeholder: https://github.com/sindresorhus/refined-github/issues
    validations:
      required: true
  - type: input
    attributes:
      label: Browser(s) used
    validations:
      required: true
