name: 🐛 Report a bug
description: ———
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting a bug! ⛰

        Help us replicate the issue by filling in this form. You can use the "Find feature" button in the option to find which feature is causing the issue.
  - type: checkboxes
    attributes:
      label: 'Please ensure:'
      options:
        - label: The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
          required: true
  - type: checkboxes
    attributes:
      label: 'Include in this issue:'
      options:
        - label: Screenshots/video/gif demonstrating the bug, if it’s visual
        - label: Console errors, if any
  - type: textarea
    attributes:
      label: Description
      description: Describe the issue and how to replicate it
    validations:
      required: true
  - type: input
    attributes:
      label: Example URL
      description: A REAL URL where the bug appears. If it happens on a private repo, find an equivalent public URL, even if it doesn't happen there.
      placeholder: https://github.com/refined-github/refined-github/issues
    validations:
      required: true
  - type: input
    attributes:
      label: Browser(s) used
    validations:
      required: true
