name: 🐛 Report a bug
description: ———
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting a bug! ⛰

        Help us replicate the issue by filling in this form. You can use the "Find feature" button in the options page to find which feature is causing the issue.

        Please ensure:

        - The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
        - The bug happens after clearing extension cache. The "Clear cache" button can be found in the options page. [](#clear-cache)

        Include in this issue:

        - Screenshots/video/gif demonstrating the bug, if it’s visual
        - Console errors, if any

  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to replicate the issue
      description: Include the steps to reproduce and A REAL URL where the bug appears. If it happens on a private repo, find an equivalent public URL, even if it doesn't happen there.
    validations:
      required: true
  - type: input
    attributes:
      label: Extension version
    validations:
      required: true
  - type: input
    attributes:
      label: Browser(s) used
    validations:
      required: true
