name: 🆕 Suggest an improvement or new feature
description: ___
labels: enhancement, under discussion
body:
  - type: textarea
    attributes:
      label: Description
      description: Please ensure your requested feature makes sense for Refined GitHub: https://github.com/sindresorhus/refined-github/issues/2960
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshot
      description: You can provide screenshots/mockups to better visualize your idea. Files can be dropped in this field
  - type: input
    attributes:
      label: Example URL
      description: Include a REAL URL where the feature should appear. e.g. Do you want a feature to appear on the main page of a repo? Paste a link to a repo
      placeholder: https://github.com/sindresorhus/refined-github
    validations:
      required: true
