name: 💬 Ask a question or open a discussion
description: Issues that don't have a specific topic
labels: under discussion
body:
  - type: textarea
    attributes:
      label: Ask a question or open a discussion
