name: 🤌 Complain
description: Is there something you don't like? Let's talk
labels: change request
body:
  - type: textarea
    attributes:
      label: Describe what part of Refined GitHub you don't like
  - type: markdown
    attributes:
      value: |
        If you find any related threads, link them here.
        Duplicate issues are ok, but they may be closed pretty quickly
