name: 👎 I don’t like something
description: Let's talk
labels: change request
body:
  - type: textarea
    attributes:
      label: "What I don't like"
      description: |
        Describe what part of Refined GitHub you don't like.

        If you find any related threads, link them here. Duplicate issues are ok, but they may be closed pretty quickly.

        Keep in mind that most features can be disabled. Use the "Find feature" button at the bottom of the options page to find what feature you don't like.
