query GetPrsToBaseBranch($owner: String!, $name: String!, $baseRefName: String!) {
	repository(owner: $owner, name: $name) {
		pullRequests(baseRefName: $baseRefName, states: OPEN) {
			totalCount
		}
	}
}
