query GetFirstCommit($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		createdAt
		defaultBranchRef {
			target {
				... on Commit {
					oid
					committedDate
					resourcePath
					history {
						totalCount
					}
				}
			}
		}
	}
}
