on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  lock-ai-spam:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: .github/workflows/daily.js

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            await require('./.github/workflows/daily.js')
             .lockAiSpam({github, context, core});
