name: RelativeCI

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  ingest:
    if: github.event.repository.fork != true
    runs-on: ubuntu-latest
    steps:
      - name: Send bundle stats and build information to RelativeCI
        uses: relative-ci/agent-action@fcf45416581928e8dd62eded78ce98c78e5149f8 # v3.2.3
        with:
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
